require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - app/admin/*.rb
    - config/environments/*.rb
    - config/routes.rb

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/patients/registrations_controller.rb
