# fly.toml app configuration file generated for small-river-8416 on 2023-06-02T15:41:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "small-river-8416"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
